- .eslintrc.js
- .travis.yml
- README.md
- config.js
- frontend/.eslintrc.js
- jest/run.js
- package.json
- postcss.config.js
- sample-data/sample-data.js
- webpack.config.js
This PR exposes lint errors in the developer console using the `eslint-loader` webpack loader:
Exposing the errors in this way makes it easier to ID and resolve issues as they occur, rather than relying on a tedious linting process prior to commit.
See MoOx/eslint-loader#78 for one issue with this approach: changes that do not affect the AST (purely stylistic things like adding a missing trailing comma) will not trigger a bundle re-build. To be sure you're seeing all available lint output, run the `npm run lint` command from the console.
**Note**: For simplicity, this PR drops CI support for Node 4, so that we can remove the es2015 modules plugin; this behavior works as expected on Node 5 and above. If this is undesirable we can reinstate the plugin but it seemed like supporting Node 6 …
> Integrate linter with dev server, and lint config & script files

- .gitignore
- README.md
- frontend/services/face-api.js
Adjusting the shape of the reducer to not expect a nested demographics key will come later in a second pass, so as not to cause a gnarly merge situation.
This also adds basic setup README instructions for OSX
> Re-point annotations API to live API demographic annotation types endpoint

- frontend/redux/__tests__/sagas.test.js
- frontend/redux/actions.js
- frontend/redux/reducers/__tests__/loading.test.js
- frontend/redux/reducers/loading.js
- frontend/redux/sagas.js
Fixes #61 by accounting for all AJAX pending states within the loading reducer, and adds test coverage for all extant sagas
> Add tests & loading state handling for all sagas

- .eslintrc.js
- frontend/redux/reducers/annotations.js
- frontend/redux/reducers/demographics.js
- frontend/redux/reducers/loading.js
- frontend/redux/reducers/workload.js
`switch ()` statements are [the convention used in the Redux docs][docs], and @gnarf had advocated for porting over our existing reducer code to reduce the delta between conventions and our own practices within this repository.
The specific improvement is that
```js
function simpleReducer(state, action) {
switch (action.type) {
case '1':
return 'Handle 1';
default:
return state;
}
}
function complexReducer(state, action) {
switch (action.type) {
case '1':
case '2':
return 'Handle 1 & 2';
default:
return state;
}
}
```
is more consistent & readable than using `if` in some place, and `if ( [].includes() )` in others, as I had been doing:
```js
function simpleReducer(state, action) {
if (action.type === '1') {
return 'Handle 1';
}
return state;
}
function complexReducer(state, action) {
if …
```
> Convert "if" statements in Reducers to use switch () {}

- frontend/components/App.styl
- frontend/components/PerceivedDemographicQuestion.jsx
- frontend/components/PerceivedDemographics.jsx
- frontend/components/PerceivedDemographics.styl
- frontend/components/ProgressBar.jsx
- frontend/components/ProgressBar.styl
- frontend/components/ProportionalContainer.jsx
- frontend/components/ProportionalContainer.styl
- frontend/components/RadioButtonOption.jsx
- frontend/components/RadioButtonOption.styl
- frontend/components/shared/mixins.styl
- package.json
- No longer possible to skip a step
- Convert radio buttons to things that look visually like buttons
- Use visual hiding, not display:none, for better accessibility
- Convert "X of Y" callouts into progress bar components
- Implement fixed proportional scaling of the image
- Introduce a mixins stylus file for code sharing
Demo:
> Re-structure annotation form for better ux flow with fewer errors

- backend/base/controller.js
- package.json
At the end of last week a new release of `eslint-plugin-react` was pushed out, unintentionally introducing a new setting that caused a breaking change. A fix was just pushed up to NPM, and updating to today's latest version resolves the issue. The maintainer has acknowledged the issue and intends to avoid similar problems going forward, so I chose to bump the dependency and reintroduce a ^ version range rather than leaving it pinned. If this bites us again we can reverse course and lock everything down!
This also fixes two unnamed-function warnings in the base controller, which have been lingering for a while -- seemed like a good time to tackle them.
> Resolve lint issues & update to reverted latest eslint react plugin tag

- .travis.yml
- package.json
The new keys in .travis.yml should improve build times.
CI flag is removed because it is no longer used to affect test behavior.
Node engine support specified as "my development version and up" in package.json,
and Node 5 removed from Travis config.
> Consistently specify Node version support, and improve Travis config

- api.md
- backend/endpoints/annotations/queries/getImages.sql
Small SQL tweak which now orders all the images based on how many annotations the annotator has done for each image, which allows the small number of "knowns" to be constantly recycled if need be.
Relates to #104
> Reuse already annotated images

- webpack.config.prod.js
Close #127
Use webpack options to add hashes of the content of js and css output
files.
Along with the hashes the names are included. So the main js bundle is
main-<hash>.js. Same for the css. With those hashes we could opt for
abbreviated ones.
A further thing we can do is modify url-loader for its file-loader fallback. The file-loader default names are just content hashes. We can add the file name so it'll be fancy-image-<hash>.png for example.
> Add content hashes to js and css distribution files

- ansible/provision.yml
- ansible/templates/nginx.conf.j2
This adds some missing config and closes gh-114 and gh-123.
Verification can happy locally by doing the following:
```
npm run provision:vagrant
npm run deploy:vagrant
```
Gzip and far-future expirations can be tested thusly:
```
curl -H "Accept-Encoding: gzip" -I http://10.10.0.100/bundle.js"
```
The response headers should include:
```
Expires: Thu, 31 Dec 2037 23:55:55 GMT
Cache-Control: max-age=315360000
Content-Encoding: gzip
```
Once landed, the following needs to be run:
```
npm run provision:production
npm run provision:staging
```
> configure nginx

- webpack.config.prod.js
Our production Webpack configuration was set up to generate a sourcemap file, but Uglify was preventing it from being output. Setting Uglify's "sourceMap" option to `true` allows this file to be generated as part of the build, which could aid in live debugging in production.
> Output a sourcemap file for the production build

- api.md
- backend/db/migrations/j0ttjlsg.count-workloads.sql
- backend/endpoints/annotations/controller.js
- backend/endpoints/annotations/queries/storeWorkload.sql
- frontend/components/ModalContainer.jsx
- frontend/components/PerceivedDemographics.jsx
- frontend/components/ProgressFeedback/ProgressFeedback.jsx
- frontend/components/ProgressFeedback/ProgressFeedback.styl
- frontend/redux/__tests__/selectors.test.js
- frontend/redux/reducers/__tests__/workload.test.js
- frontend/redux/reducers/workload.js
- frontend/redux/selectors.js
- frontend/services/content.js
Closes #74
This implements an interface that shows an annotator encouraging messages as they complete more workloads. The implementation is driven by a new `completeCount` field provided on the Workload API response; on the first step of a new workload (_i.e._, the first image in a workload AND the first annotation step for that image), a predetermined message is displayed to the annotator depending on their progress.
Current messages are for:
- Starting your first workload
- Completing your first workload
- Completing your second workload
- Completing your third workload
- Completing any multiple of 10 workloads
The copy should be considered placeholder, but I did try to avoid using the actual term "workload," as I felt it connotes that we were placing a job or a burden on the annotator. …
> Implement UI feedback for workload completion progression

- backend/db/migrations/j0tkounk.update-labels.sql
Fixes #148 (but you need to migrate:reset or migrate:down until you revert "update-labels" and then migrate:up to fix it)
> Fix migrations to have typo

- ansible/inventory/production
This requires running `npm run provision:production` (which I have done--this change is currently live).
> make canonical domain ajl.ai - closes gh-149

- backend/endpoints/annotations/controller.js
- backend/endpoints/annotations/queries/getOverallStats.sql
- backend/endpoints/annotations/routes.js
- frontend/components/Home.jsx
- frontend/components/KnownOverallProgress.jsx
- frontend/components/KnownOverallProgress.styl
- frontend/components/KnownOverallProgressContainer.jsx
- frontend/redux/actions.js
- frontend/redux/reducers.js
- frontend/redux/reducers/overall-stats.js
- frontend/redux/sagas.js
- frontend/redux/selectors.js
- frontend/services/api.js
- frontend/services/content.js
Closes #118.
- Add a `/annotations/overall-stats` api endpoint
- Add api services, redux actions and sagas for requesting `overall-stats`
- Add a KnownOverallProgress component and container
- Add KnownOverallProgress to Home
`overall-stats` currently returns `known_count` and `total_count`. With those two values we can add a basic progress bar with some information about the global progress of the project to the Home page. `overall-stats` with its name may also be a good place for us to expand the information of the projects progress.
> Implement Global Annotation Progress on Home

- webpack.config.prod.js
When we build our production bundle, this is what we get:
```
Asset       Size  Chunks                    Chunk Names
main-cb910c189f1405adaf68.min.js     448 kB       0  [emitted]  [big]  main
main-70a302a379274539c79d313d674f80b0.css     8.8 kB       0  [emitted]         main
main-70a302a379274539c79d313d674f80b0.css.map  118 bytes       0  [emitted]         main
index.html  544 bytes          [emitted]
[8] ../~/react/react.js 56 bytes {0} [built]
```
Not bad, but we can do better. A lot of code within React (and some within our own app, such as the store logging middleware) is gated by a check that NODE_ENV !== "production"; we can use the DefinePlugin to hard-code that value before Uglify runs, so that any gated code can be removed entirely.
```
Asset       Size  Chunks …
```
> Configure NODE_ENV to "production" when building prod bundle

- frontend/components/PerceivedDemographics.styl
- frontend/components/RangeSlider.jsx
I made some improvements to the current age slider. Here a screenshot of how it looks:
As a side note I would like to point out that I couldn't figure out for this PR how to set a default value. Right now every time the user annotates an image and gets back to the first step, they will see the value they selected for the previous image, which is not ideal.
> Improve age slider UX (#163 )

- backend/db/migrations/j16lc8mk.flagging-view.sql
- backend/endpoints/annotations/queries/getImages.sql
- backend/endpoints/annotations/queries/getOverallStats.sql
Finishes #136 
Images are now not selected after reaching the "flagged" threshold which is defined as `flags > 1 AND flags > annotations`
I defined the query powering this as a VIEW so that it could be reused in a few places (and updated the get overall stats to use that as an example)
> Rework calculation of image workload

- ansible/vars/main.yml
As per @tkellen's request, here's a PR clarifying how the secrets variable is setup. In particular, I initially found it confusing thinking that `vault` was a special keyword since I hadn't looked inside the secrets.yml file.
> Clarify where vault is populated

- ansible/deploy.yml
As per @tkellen's recommendation, this change makes sure a symlink is made to a previously deployed directory before failing the build. It should enable modifying the `commit` variable and running the deploy playbook again to switch to that commit if it is in the last 3 deployed commits (i.e., it has a folder on the server).
> Add check to ensure rolled back deploy is symlinked

- .gitignore
- ansible/download-annotations.yml
- backend/db/migrations/j1m9znv3.report-view.sql
- package.json
Adds `npm run download-annotations` which makes an `annotations.csv`
I deployed the migration to the production server already, so you can test this command.
Closes #206
> Csv report

- ansible/ssl.yml
this should ensure letsencrypt ssl certificates automatically
renew when they expire.
> specify user and file for ssl renewal cronjob

- ansible/ssl.yml
/usr/local/bin was not in PATH
> use full path to dehydrated to ensure certs auto renew
