bocoup/ajl.ai

- image-annotator/.babelrc
- image-annotator/.eslintrc.js
- image-annotator/jest/fileStub.js
- image-annotator/jest/run.js
- image-annotator/package.json
- image-annotator/src/__tests__/hello-world.test.js
Closes #5 : run tests with `npm test` within the image-annotator/ subdirectly.
> Add Jest to project for unit testing

- README.md
- image-annotator/.eslintrc.js
- image-annotator/src/components/Carousel.jsx
- image-annotator/src/components/Carousel.styl
- image-annotator/src/containers/CanvasContainer.jsx
- image-annotator/src/containers/CarouselContainer.jsx
- image-annotator/src/redux/__tests__/reducers.test.js
- image-annotator/src/redux/__tests__/sagas.test.js
- image-annotator/src/redux/__tests__/selectors.test.js
- image-annotator/src/redux/actions.js
- image-annotator/src/redux/reducers.js
- image-annotator/src/redux/reducers/__tests__/faces.test.js
- image-annotator/src/redux/reducers/__tests__/loading.test.js
- image-annotator/src/redux/reducers/faces.js
- image-annotator/src/redux/reducers/loading.js
- image-annotator/src/redux/sagas.js
- image-annotator/src/redux/selectors.js
- image-annotator/src/utils/deep-freeze.js
This PR contains the remainder of the work I was able to accomplish next week, with a focus on implementing React components and a full Redux flow (to handle scrolling through the images) which can serve as a model for future development.
As time permits I would love @gnarf to critique this one to bits, and I'd like to do a full app code walkthrough with @boazsender some time in the next day
> Add complete React/Redux scaffold for image carousel behavior

- README.md
- image-annotator/src/components/App.jsx
- image-annotator/src/components/Canvas.styl
- image-annotator/src/components/CanvasContainer.jsx
- image-annotator/src/components/Carousel.jsx
- image-annotator/src/components/Carousel.styl
- image-annotator/src/components/CarouselContainer.jsx
- image-annotator/src/components/LoadingContainer.jsx
- image-annotator/src/components/LoadingIndicator.jsx
- image-annotator/src/components/LoadingIndicator.styl
- image-annotator/src/global.styl
- image-annotator/src/redux/reducers/__tests__/faces.test.js
- image-annotator/src/redux/reducers/faces.js
- image-annotator/src/redux/reducers/loading.js
This moves the ___Container components into the main component directory; having a separate directory felt more confusing than less (at this stage).
A Loading indicator is also added that displays while data is fetching, as an example of how to implement a new connected component.
> Move all components into same directory and add loading component

- package.json
Seems to resolve my router context issue
> Upgrade React-Router-DOM package to beta.7 to fix bug

- .travis.yml
- frontend/components/App.jsx
- frontend/components/Canvas.jsx
- frontend/components/Home.jsx
- frontend/components/Landmarks.jsx
- frontend/components/PerceivedDemographics.jsx
- frontend/components/Regions.jsx
- frontend/index.jsx
- frontend/services/__tests__/face-api.test.js
- package.json
- Resolves lint errors in the master branch
- Resolves unit test failures in the master branch
- Adds `.travis.yml` file to add continuous integration via travis-ci.org
> Resolve lint & test errors and integrate Travis CI

- frontend/components/Landmarks.jsx
- frontend/components/LandmarksContainer.jsx
- frontend/components/Regions.jsx
- frontend/components/RegionsContainer.jsx
This should be merged before #36
> Resolve lint errors in region landmarks branch

- frontend/components/Landmarks.jsx
- frontend/components/LandmarksContainer.jsx
- frontend/components/PerceivedDemographics.jsx
- frontend/components/PerceivedDemographicsContainer.jsx
- frontend/components/Regions.jsx
- frontend/components/RegionsContainer.jsx
- frontend/redux/__tests__/reducers.test.js
- frontend/redux/__tests__/sagas.test.js
- frontend/redux/__tests__/selectors.test.js
- frontend/redux/actions.js
- frontend/redux/reducers.js
- frontend/redux/reducers/__tests__/annotations.js
- frontend/redux/reducers/__tests__/demographics.test.js
- frontend/redux/reducers/__tests__/workload.test.js
- frontend/redux/reducers/annotations.js
- frontend/redux/reducers/demographics.js
- frontend/redux/reducers/loading.js
- frontend/redux/reducers/workload.js
- frontend/redux/sagas.js
- frontend/redux/selectors.js
For #16 / #54
- Allows us to update our idioms from demographics answer to "image annotation"
- Maintains the state in the format the server expects
- Allows creation of a non-transformative selector for image annotations
> Refactor state

- frontend/redux/store.js
> Use redux devtools extension when available

- README.md
In an effort to standardize how we refer to different objects within our data model in a future-oriented way, this PR adds a glossary of terms to the README:
This section clarifies the verbiage and terms used within the application code.
An **attribute** is the object representing a specific type of annotation a user will apply to any given image, such as demographic attributes like "perceived ethnicity" or positional attributes like "the location of the right eye."
Attribute properties:
- **Name**: the human-oriented label of an attribute, such as "Perceived Gender."
- **Type**: the type of data represented by the attribute, *e.g.* a list of multiple-choice options, or a set of coordinates, etc. _Note: This is a database- / data model-oriented value, and has no inherent correspondence to …
> Add glossary of terms to README

- backend/db/migrations/j08lbh0w.known.sql
- backend/endpoints/annotations/controller.js
- backend/endpoints/annotations/queries/getImages.sql
add concept of known truths, seed with 15 knowns, and update API to consider them.
WIP not ready to merge
> introduce known annotations (consensus and seeded)

- backend/endpoints/annotations/controller.js
This should fix the out of truths error, we still need a better behavior figured out for this case in #101
> Fix ran out of known truths error

- api.md
- backend/db/migrations/izzxnkr3.image-seed.sql
- backend/db/migrations/j0lb83if.attributes.sql
- backend/endpoints/annotations/controller.js
- backend/endpoints/annotations/queries/getAttributes.sql
- backend/endpoints/annotations/queries/getImages.sql
- backend/endpoints/annotations/queries/getKnownAnnotations.sql
- backend/endpoints/annotations/queries/getTypes.sql
- backend/endpoints/annotations/queries/postAnnotations.sql
- backend/endpoints/annotations/routes.js
- frontend/services/__tests__/api.test.js
- frontend/services/api.js
Update backend to `annotation_attribute` instead of `annotation_type`
> Rename annotation_type to annotation_attribute

- .storybook/config.js
- .storybook/decorators.jsx
- frontend/components/App.jsx
- frontend/components/Header/Header.jsx
- frontend/components/Header/Header.stories.jsx
- frontend/components/Header/Header.styl
add Story decorator to add History context
Question: @gnarf I tried to follow the example you provided but I can't get the Link elements to render without error. Any advice?
> WIP: Add Header component

- frontend/components/App.jsx
- frontend/components/ModalContainer.jsx
- frontend/redux/reducers/__tests__/errors.test.js
- frontend/redux/reducers/errors.js
- frontend/services/error-props.js
This improves the user experience with the existing error system, completing the work covered by #53
> Improve UX flow when errors occur

- backend/endpoints/annotations/controller.js
> Replace "enrollment" with "repeatAnnotator" flag for session

- frontend/components/App.styl
- frontend/components/PerceivedDemographicQuestion.jsx
- frontend/components/PerceivedDemographics.jsx
- frontend/components/PerceivedDemographics.styl
- frontend/components/ProgressBar/ProgressBar.styl
- frontend/components/RadioButtonOption.styl
- frontend/components/shared/mixins.styl
- frontend/index.html
This Pull Request includes some progress on the overall look and feel of the app.
> Ui improvements

- backend/db/migrations/j0tx6htl.timestamps.sql
- backend/endpoints/annotations/queries/scoreWorkload.sql
Closes #90 
* Logs time that workload is given to user
* Logs time that annotation is recorded
> Log timestamps

- backend/db/migrations/j0tkounk.update-labels.sql
- backend/endpoints/annotations/queries/getAttributes.sql
Closes #116 
Updates the labels for gender and ethnicity, left age alone for now - we may still want to "Proper Case" them since the others are now proper cased.
> Update Demographics Labels and knowns

- frontend/components/App.styl
- frontend/components/Header/Header.styl
- frontend/components/PerceivedDemographicQuestion.jsx
- frontend/components/PerceivedDemographics.jsx
- frontend/components/PerceivedDemographics.styl
- frontend/components/ProgressBar/ProgressBar.styl
- frontend/components/shared/mixins.styl
This PR includes the final details for the Demographics Page look and feel
One kind of drastic change I made, was moving the back button to the top (as you can see in the screenshot). I consider this more intuitive than having it at the bottom. What do you all think?
> Final details of Demographics view

- backend/db/migrations/j13nqgv1.remove-score.sql
- backend/endpoints/annotations/controller.js
- backend/endpoints/annotations/queries/completeWorkload.sql
- backend/endpoints/annotations/queries/getWorkload.sql
- backend/endpoints/annotations/queries/scoreWorkload.sql
- backend/endpoints/annotations/queries/storeWorkload.sql
> Remove score calculation code, replace with counting "submitted_at"

- backend/db/migrations/j12bouy3.age-range.sql
- backend/endpoints/annotations/queries/getAttributes.sql
- frontend/components/PerceivedDemographicQuestion.jsx
- frontend/components/PerceivedDemographics.jsx
- frontend/components/PerceivedDemographics.styl
- frontend/components/RangeSlider.jsx
This converts the age to a bunch of options :)
Bonus points: The frontend still handles this change (though the ui is ugly)
> WIP: Update to store a range from 10-100 for age

- frontend/components/App.jsx
- frontend/components/App.styl
@boazsender and @joyab I was reconsidering this and came up with a new idea. Instead having simple homepage and contact form links, I turned this into (what could be) the trigger to open the Feedback dialog with a call to action to do so. Here's a screenshot:
Note: The feedback modal is in a different branch (#120), so we'll need to land this first and the add functionality to the modal afterwards.
> Styling Footer (#161)

- frontend/components/Overlays/Modal.jsx
- frontend/components/Overlays/Modal.styl
Modals have been styled and they look like this:
> Styling modals (#170)

- backend/db/migrations/j150pybi.flag-attributes.sql
- backend/endpoints/annotations/queries/getAttributes.sql
- frontend/components/PerceivedDemographicQuestion.jsx
- frontend/components/PerceivedDemographics.jsx
- frontend/components/PerceivedDemographics.styl
- frontend/components/PerceivedDemographicsContainer.jsx
- frontend/redux/__tests__/selectors.test.js
- frontend/redux/actions.js
- frontend/redux/reducers/__tests__/annotations.js
- frontend/redux/reducers/__tests__/demographic-attributes.test.js
- frontend/redux/reducers/__tests__/workload.test.js
- frontend/redux/reducers/annotations.js
- frontend/redux/reducers/demographic-attributes.js
- frontend/redux/reducers/workload.js
- frontend/redux/selectors.js
This is a WIP and should give @kadamwhite the backend needed to create the front end for flagging.
> Add a flag attribute / flagging options

- frontend/components/PerceivedDemographics.jsx
Bug that boaz brought up in #188
> Fix flag last

- frontend/components/App.jsx
- frontend/components/Header/Header.jsx
- frontend/components/Header/Header.styl
- frontend/components/HeaderContainer.jsx
- frontend/components/ModalContainer.jsx
- frontend/components/Overlays/FeedbackModal.jsx
- frontend/components/Overlays/FeedbackModal.styl
- frontend/components/ProgressFeedback/ProgressFeedback.jsx
- frontend/redux/__tests__/reducers.test.js
- frontend/redux/__tests__/selectors.test.js
- frontend/redux/actions.js
- frontend/redux/reducers.js
- frontend/redux/reducers/__tests__/ui.test.js
- frontend/redux/reducers/ui.js
- frontend/redux/selectors.js
Pretty basic, but here's the wired-up feedback modal:
> Implement a feedback modal

- frontend/components/App.styl
- frontend/components/Footer/Footer.styl
- frontend/components/Home.jsx
- frontend/components/ModalContainer.jsx
- frontend/components/Overlays/AgeConsentModal.jsx
- frontend/components/Overlays/Modal.styl
- frontend/components/PerceivedDemographicsContainer.jsx
- frontend/redux/__tests__/selectors.test.js
- frontend/redux/actions.js
- frontend/redux/reducers/__tests__/ui.test.js
- frontend/redux/reducers/ui.js
- frontend/redux/selectors.js
- frontend/services/content.js
> add age consent, and FAQ onboarding workflow

- ansible/templates/.pgpass.j2
This resolves a regression introduced in https://github.com/bocoup/image-annotator/commit/b6b60353b0a738c5c10465a9bc4c8906018c3b93
> use PGPASSWORD var for .pgpass file

- frontend/components/PerceivedDemographics.styl
- frontend/components/RangeSlider.jsx
> remove leading age, step in 5s, and move age above the thumb

- README.md
> documentation for reporting

- backend/db/migrations/j30pxbc5.update-labels.sql
- frontend/components/PerceivedDemographics.jsx
- frontend/components/PerceivedDemographics.styl
- frontend/components/RangeSlider.jsx
This is a partial completion of the tasks on #216.
This is ready for review, and to be merged.
> 216 user flow

- frontend/components/App.styl
- frontend/components/Home.jsx
- frontend/components/Home.styl
- frontend/components/KnownOverallProgress.jsx
- frontend/components/Overlays/AgeConsentModal.jsx
- frontend/components/shared/mixins.styl
- package.json
Fixed lint errors from previously failed pull request. Should be ready to deploy.
> added onboarding design and language to home page, updated home and global styles

- backend/db/migrations/j7e4y0sq.update-image-loc.sql
- backend/db/migrations/j7e642uq.change-flag-order.sql
- backend/endpoints/annotations/queries/getAttributes.sql
- frontend/components/PerceivedDemographics.jsx
- frontend/components/PerceivedDemographics.styl
- frontend/redux/reducers/demographic-attributes.js
- frontend/redux/reducers/overall-stats.js
> This PR turns flagging on default

- ansible/database-restore.yml
- ansible/deploy.yml
- ansible/provision.yml
> fix ansible deprecations

- backend/db/migrations/j94s4jky.annotator-demographics.sql
- backend/endpoints/annotator/controller.js
- backend/endpoints/annotator/queries/index.js
- backend/endpoints/annotator/queries/postAnnotatorDemographics.sql
- backend/endpoints/annotator/routes.js
- backend/endpoints/index.js
- frontend/components/PerceivedDemographics.jsx
- frontend/components/PerceivedDemographics.styl
- frontend/components/PerceivedDemographicsContainer.jsx
- frontend/redux/actions.js
- frontend/redux/sagas.js
- frontend/services/api.js
Test by going through the annotation flow as a first time ("unenrolled") annotator. You should be prompted to label your own demographics..
> Add annotator demographics
